FROM nginx

ARG SHOW_VALUE

COPY ./nginx.conf /etc/nginx/nginx.conf

RUN mkdir /etc/nginx/html/
RUN echo $SHOW_VALUE > /etc/nginx/html/content.txt
RUN chmod -R 755 /etc/nginx/html/content.txt

ENV TZ=America/Sao_Paulo

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]