apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: driven
spec:
  selector:
    side: driven
  ports:
    - port: 80

---

apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: driven
spec:
  type: ExternalName
  externalName: host.minikube.internal