apiVersion: v1
kind: Pod
metadata:
  namespace: test
  name: driven-test
  labels:
    side: driven
spec:
  containers:
    - name: driven-test
      image: driven:test
      imagePullPolicy: Never
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
