apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: queue
  labels:
    app: work-queue
    component: queue
    chapter: job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: work-queue
      component: queue
      chapter: job
  template:
    metadata:
      labels:
        app: work-queue
        component: queue
        chapter: job
    spec:
      containers:
        - name: queue
          image: gcr.io/kuar-demo/kuard-amd64:blue