apiVersion: v1
kind: Pod
metadata:
  name: alpaca-test
  labels:
    ver: "2"
    app: alpaca
    env: prod
spec:
  containers:
    - name: kuard
      image: gcr.io/kuar-demo/kuard-amd64:blue
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"