apiVersion: v1
kind: Pod
metadata:
  name: brandicoot-staging
  labels:
    ver: "2"
    app: brandicoot
    env: staging
spec:
  containers:
    - name: kuard
      image: gcr.io/kuar-demo/kuard-amd64:blue
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"