apiVersion: v1
kind: Pod
metadata:
  name: brandicoot-prod
  labels:
    ver: "2"
    app: brandicoot
    env: prod
spec:
  containers:
    - name: kuard
      image: gcr.io/kuar-demo/kuard-amd64:green
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080