apiVersion: v1
kind: Pod
metadata:
  name: alpaca
  labels:
    ver: "1"
    app: alpaca
    env: prod
spec:
  containers:
    - name: kuard
      image: gcr.io/kuar-demo/kuard-amd64:blue
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: alpaca
spec:
  type: NodePort
  selector:
    app: alpaca
  ports:
    - port: 8080