apiVersion: v1
kind: Pod
metadata:
  name: be-default
  labels:
    app: be-default
spec:
  containers:
    - name: kuard
      image: gcr.io/kuar-demo/kuard-amd64:blue
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: be-default
spec:
  type: NodePort
  selector:
    app: be-default
  ports:
    - port: 8080