apiVersion: batch/v1
kind: Job
metadata:
  name: parallel
spec: 
  parallelism: 5
  completions: 10
  template:
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:blue
        command: ["/kuard"]
        args:
          - "--keygen-enable"
          - "--keygen-exit-on-complete"
          - "--keygen-num-to-gen=10"
      restartPolicy: OnFailure